# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 720)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 1024, 700))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.lbl_lumber = QtGui.QLabel(self.tab)
        self.lbl_lumber.setGeometry(QtCore.QRect(50, 40, 250, 20))
        self.lbl_lumber.setObjectName(_fromUtf8("lbl_lumber"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(360, 250, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.btn_update = QtGui.QPushButton(self.tab)
        self.btn_update.setGeometry(QtCore.QRect(610, 450, 75, 23))
        self.btn_update.setObjectName(_fromUtf8("btn_update"))
        self.lbl_icon_lumber = QtGui.QLabel(self.tab)
        self.lbl_icon_lumber.setGeometry(QtCore.QRect(20, 40, 20, 20))
        self.lbl_icon_lumber.setText(_fromUtf8(""))
        self.lbl_icon_lumber.setPixmap(QtGui.QPixmap(_fromUtf8("../Users/Daemon/.designer/backup/images/lumber_small.png")))
        self.lbl_icon_lumber.setObjectName(_fromUtf8("lbl_icon_lumber"))
        self.lbl_header = QtGui.QLabel(self.tab)
        self.lbl_header.setGeometry(QtCore.QRect(20, 20, 200, 20))
        self.lbl_header.setText(_fromUtf8(""))
        self.lbl_header.setObjectName(_fromUtf8("lbl_header"))
        self.lbl_icon_clay = QtGui.QLabel(self.tab)
        self.lbl_icon_clay.setGeometry(QtCore.QRect(20, 60, 20, 20))
        self.lbl_icon_clay.setText(_fromUtf8(""))
        self.lbl_icon_clay.setPixmap(QtGui.QPixmap(_fromUtf8("../Users/Daemon/.designer/backup/images/clay_small.png")))
        self.lbl_icon_clay.setObjectName(_fromUtf8("lbl_icon_clay"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(290, 330, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.lbl_icon_iron = QtGui.QLabel(self.tab)
        self.lbl_icon_iron.setGeometry(QtCore.QRect(20, 80, 20, 20))
        self.lbl_icon_iron.setText(_fromUtf8(""))
        self.lbl_icon_iron.setPixmap(QtGui.QPixmap(_fromUtf8("../Users/Daemon/.designer/backup/images/iron_small.png")))
        self.lbl_icon_iron.setObjectName(_fromUtf8("lbl_icon_iron"))
        self.lbl_icon_crop = QtGui.QLabel(self.tab)
        self.lbl_icon_crop.setGeometry(QtCore.QRect(20, 100, 20, 20))
        self.lbl_icon_crop.setText(_fromUtf8(""))
        self.lbl_icon_crop.setPixmap(QtGui.QPixmap(_fromUtf8("../Users/Daemon/.designer/backup/images/oasis_small.png")))
        self.lbl_icon_crop.setObjectName(_fromUtf8("lbl_icon_crop"))
        self.lbl_clay = QtGui.QLabel(self.tab)
        self.lbl_clay.setGeometry(QtCore.QRect(50, 60, 250, 20))
        self.lbl_clay.setObjectName(_fromUtf8("lbl_clay"))
        self.lbl_iron = QtGui.QLabel(self.tab)
        self.lbl_iron.setGeometry(QtCore.QRect(50, 80, 250, 20))
        self.lbl_iron.setObjectName(_fromUtf8("lbl_iron"))
        self.lbl_crop = QtGui.QLabel(self.tab)
        self.lbl_crop.setGeometry(QtCore.QRect(50, 100, 250, 20))
        self.lbl_crop.setObjectName(_fromUtf8("lbl_crop"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.lbl_id1_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id1_icon.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.lbl_id1_icon.setText(_fromUtf8(""))
        self.lbl_id1_icon.setObjectName(_fromUtf8("lbl_id1_icon"))
        self.lbl_id2_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id2_icon.setGeometry(QtCore.QRect(10, 60, 40, 40))
        self.lbl_id2_icon.setText(_fromUtf8(""))
        self.lbl_id2_icon.setObjectName(_fromUtf8("lbl_id2_icon"))
        self.lbl_id3_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id3_icon.setGeometry(QtCore.QRect(10, 110, 40, 40))
        self.lbl_id3_icon.setText(_fromUtf8(""))
        self.lbl_id3_icon.setObjectName(_fromUtf8("lbl_id3_icon"))
        self.lbl_id4_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id4_icon.setGeometry(QtCore.QRect(10, 160, 40, 40))
        self.lbl_id4_icon.setText(_fromUtf8(""))
        self.lbl_id4_icon.setObjectName(_fromUtf8("lbl_id4_icon"))
        self.lbl_id5_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id5_icon.setGeometry(QtCore.QRect(10, 210, 40, 40))
        self.lbl_id5_icon.setText(_fromUtf8(""))
        self.lbl_id5_icon.setObjectName(_fromUtf8("lbl_id5_icon"))
        self.lbl_id6_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id6_icon.setGeometry(QtCore.QRect(10, 260, 40, 40))
        self.lbl_id6_icon.setText(_fromUtf8(""))
        self.lbl_id6_icon.setObjectName(_fromUtf8("lbl_id6_icon"))
        self.lbl_id7_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id7_icon.setGeometry(QtCore.QRect(10, 310, 40, 40))
        self.lbl_id7_icon.setText(_fromUtf8(""))
        self.lbl_id7_icon.setObjectName(_fromUtf8("lbl_id7_icon"))
        self.lbl_id8_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id8_icon.setGeometry(QtCore.QRect(10, 360, 40, 40))
        self.lbl_id8_icon.setText(_fromUtf8(""))
        self.lbl_id8_icon.setObjectName(_fromUtf8("lbl_id8_icon"))
        self.lbl_id9_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id9_icon.setGeometry(QtCore.QRect(10, 410, 40, 40))
        self.lbl_id9_icon.setText(_fromUtf8(""))
        self.lbl_id9_icon.setObjectName(_fromUtf8("lbl_id9_icon"))
        self.lbl_id1 = QtGui.QLabel(self.tab_2)
        self.lbl_id1.setGeometry(QtCore.QRect(60, 20, 120, 20))
        self.lbl_id1.setMouseTracking(False)
        self.lbl_id1.setText(_fromUtf8(""))
        self.lbl_id1.setObjectName(_fromUtf8("lbl_id1"))
        self.lbl_id2 = QtGui.QLabel(self.tab_2)
        self.lbl_id2.setGeometry(QtCore.QRect(60, 70, 120, 20))
        self.lbl_id2.setText(_fromUtf8(""))
        self.lbl_id2.setObjectName(_fromUtf8("lbl_id2"))
        self.lbl_id3 = QtGui.QLabel(self.tab_2)
        self.lbl_id3.setGeometry(QtCore.QRect(60, 120, 120, 20))
        self.lbl_id3.setText(_fromUtf8(""))
        self.lbl_id3.setObjectName(_fromUtf8("lbl_id3"))
        self.lbl_id4 = QtGui.QLabel(self.tab_2)
        self.lbl_id4.setGeometry(QtCore.QRect(60, 170, 120, 20))
        self.lbl_id4.setText(_fromUtf8(""))
        self.lbl_id4.setObjectName(_fromUtf8("lbl_id4"))
        self.lbl_id5 = QtGui.QLabel(self.tab_2)
        self.lbl_id5.setGeometry(QtCore.QRect(60, 220, 120, 20))
        self.lbl_id5.setText(_fromUtf8(""))
        self.lbl_id5.setObjectName(_fromUtf8("lbl_id5"))
        self.lbl_id6 = QtGui.QLabel(self.tab_2)
        self.lbl_id6.setGeometry(QtCore.QRect(60, 270, 120, 20))
        self.lbl_id6.setText(_fromUtf8(""))
        self.lbl_id6.setObjectName(_fromUtf8("lbl_id6"))
        self.lbl_id7 = QtGui.QLabel(self.tab_2)
        self.lbl_id7.setGeometry(QtCore.QRect(60, 320, 120, 20))
        self.lbl_id7.setText(_fromUtf8(""))
        self.lbl_id7.setObjectName(_fromUtf8("lbl_id7"))
        self.lbl_id8 = QtGui.QLabel(self.tab_2)
        self.lbl_id8.setGeometry(QtCore.QRect(60, 370, 120, 20))
        self.lbl_id8.setText(_fromUtf8(""))
        self.lbl_id8.setObjectName(_fromUtf8("lbl_id8"))
        self.lbl_id9 = QtGui.QLabel(self.tab_2)
        self.lbl_id9.setGeometry(QtCore.QRect(60, 420, 180, 20))
        self.lbl_id9.setText(_fromUtf8(""))
        self.lbl_id9.setObjectName(_fromUtf8("lbl_id9"))
        self.lbl_id10_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id10_icon.setGeometry(QtCore.QRect(250, 10, 40, 40))
        self.lbl_id10_icon.setText(_fromUtf8(""))
        self.lbl_id10_icon.setObjectName(_fromUtf8("lbl_id10_icon"))
        self.lbl_id14 = QtGui.QLabel(self.tab_2)
        self.lbl_id14.setGeometry(QtCore.QRect(300, 220, 120, 20))
        self.lbl_id14.setText(_fromUtf8(""))
        self.lbl_id14.setObjectName(_fromUtf8("lbl_id14"))
        self.lbl_id10 = QtGui.QLabel(self.tab_2)
        self.lbl_id10.setGeometry(QtCore.QRect(300, 20, 120, 20))
        self.lbl_id10.setText(_fromUtf8(""))
        self.lbl_id10.setObjectName(_fromUtf8("lbl_id10"))
        self.lbl_id13_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id13_icon.setGeometry(QtCore.QRect(250, 160, 40, 40))
        self.lbl_id13_icon.setText(_fromUtf8(""))
        self.lbl_id13_icon.setObjectName(_fromUtf8("lbl_id13_icon"))
        self.lbl_id13 = QtGui.QLabel(self.tab_2)
        self.lbl_id13.setGeometry(QtCore.QRect(300, 170, 120, 20))
        self.lbl_id13.setText(_fromUtf8(""))
        self.lbl_id13.setObjectName(_fromUtf8("lbl_id13"))
        self.lbl_id18 = QtGui.QLabel(self.tab_2)
        self.lbl_id18.setGeometry(QtCore.QRect(300, 420, 180, 20))
        self.lbl_id18.setText(_fromUtf8(""))
        self.lbl_id18.setObjectName(_fromUtf8("lbl_id18"))
        self.lbl_id17_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id17_icon.setGeometry(QtCore.QRect(250, 360, 40, 40))
        self.lbl_id17_icon.setText(_fromUtf8(""))
        self.lbl_id17_icon.setObjectName(_fromUtf8("lbl_id17_icon"))
        self.lbl_id12 = QtGui.QLabel(self.tab_2)
        self.lbl_id12.setGeometry(QtCore.QRect(300, 120, 120, 20))
        self.lbl_id12.setText(_fromUtf8(""))
        self.lbl_id12.setObjectName(_fromUtf8("lbl_id12"))
        self.lbl_id17 = QtGui.QLabel(self.tab_2)
        self.lbl_id17.setGeometry(QtCore.QRect(300, 370, 120, 20))
        self.lbl_id17.setText(_fromUtf8(""))
        self.lbl_id17.setObjectName(_fromUtf8("lbl_id17"))
        self.lbl_id18_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id18_icon.setGeometry(QtCore.QRect(250, 410, 40, 40))
        self.lbl_id18_icon.setText(_fromUtf8(""))
        self.lbl_id18_icon.setObjectName(_fromUtf8("lbl_id18_icon"))
        self.lbl_id12_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id12_icon.setGeometry(QtCore.QRect(250, 110, 40, 40))
        self.lbl_id12_icon.setText(_fromUtf8(""))
        self.lbl_id12_icon.setObjectName(_fromUtf8("lbl_id12_icon"))
        self.lbl_id14_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id14_icon.setGeometry(QtCore.QRect(250, 210, 40, 40))
        self.lbl_id14_icon.setText(_fromUtf8(""))
        self.lbl_id14_icon.setObjectName(_fromUtf8("lbl_id14_icon"))
        self.lbl_id16_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id16_icon.setGeometry(QtCore.QRect(250, 310, 40, 40))
        self.lbl_id16_icon.setText(_fromUtf8(""))
        self.lbl_id16_icon.setObjectName(_fromUtf8("lbl_id16_icon"))
        self.lbl_id16 = QtGui.QLabel(self.tab_2)
        self.lbl_id16.setGeometry(QtCore.QRect(300, 320, 120, 20))
        self.lbl_id16.setText(_fromUtf8(""))
        self.lbl_id16.setObjectName(_fromUtf8("lbl_id16"))
        self.lbl_id11 = QtGui.QLabel(self.tab_2)
        self.lbl_id11.setGeometry(QtCore.QRect(300, 70, 120, 20))
        self.lbl_id11.setText(_fromUtf8(""))
        self.lbl_id11.setObjectName(_fromUtf8("lbl_id11"))
        self.lbl_id11_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id11_icon.setGeometry(QtCore.QRect(250, 60, 40, 40))
        self.lbl_id11_icon.setText(_fromUtf8(""))
        self.lbl_id11_icon.setObjectName(_fromUtf8("lbl_id11_icon"))
        self.lbl_id15_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id15_icon.setGeometry(QtCore.QRect(250, 260, 40, 40))
        self.lbl_id15_icon.setText(_fromUtf8(""))
        self.lbl_id15_icon.setObjectName(_fromUtf8("lbl_id15_icon"))
        self.lbl_id15 = QtGui.QLabel(self.tab_2)
        self.lbl_id15.setGeometry(QtCore.QRect(300, 270, 120, 20))
        self.lbl_id15.setText(_fromUtf8(""))
        self.lbl_id15.setObjectName(_fromUtf8("lbl_id15"))
        self.lbl_id34_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id34_icon.setGeometry(QtCore.QRect(730, 310, 40, 40))
        self.lbl_id34_icon.setText(_fromUtf8(""))
        self.lbl_id34_icon.setObjectName(_fromUtf8("lbl_id34_icon"))
        self.lbl_id19_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id19_icon.setGeometry(QtCore.QRect(490, 10, 40, 40))
        self.lbl_id19_icon.setText(_fromUtf8(""))
        self.lbl_id19_icon.setObjectName(_fromUtf8("lbl_id19_icon"))
        self.lbl_id31 = QtGui.QLabel(self.tab_2)
        self.lbl_id31.setGeometry(QtCore.QRect(780, 170, 120, 20))
        self.lbl_id31.setText(_fromUtf8(""))
        self.lbl_id31.setObjectName(_fromUtf8("lbl_id31"))
        self.lbl_id23 = QtGui.QLabel(self.tab_2)
        self.lbl_id23.setGeometry(QtCore.QRect(540, 220, 120, 20))
        self.lbl_id23.setText(_fromUtf8(""))
        self.lbl_id23.setObjectName(_fromUtf8("lbl_id23"))
        self.lbl_id19 = QtGui.QLabel(self.tab_2)
        self.lbl_id19.setGeometry(QtCore.QRect(540, 20, 120, 20))
        self.lbl_id19.setText(_fromUtf8(""))
        self.lbl_id19.setObjectName(_fromUtf8("lbl_id19"))
        self.lbl_id33_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id33_icon.setGeometry(QtCore.QRect(730, 260, 40, 40))
        self.lbl_id33_icon.setText(_fromUtf8(""))
        self.lbl_id33_icon.setObjectName(_fromUtf8("lbl_id33_icon"))
        self.lbl_id32_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id32_icon.setGeometry(QtCore.QRect(730, 210, 40, 40))
        self.lbl_id32_icon.setText(_fromUtf8(""))
        self.lbl_id32_icon.setObjectName(_fromUtf8("lbl_id32_icon"))
        self.lbl_id35 = QtGui.QLabel(self.tab_2)
        self.lbl_id35.setGeometry(QtCore.QRect(780, 370, 120, 20))
        self.lbl_id35.setText(_fromUtf8(""))
        self.lbl_id35.setObjectName(_fromUtf8("lbl_id35"))
        self.lbl_id22_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id22_icon.setGeometry(QtCore.QRect(490, 160, 40, 40))
        self.lbl_id22_icon.setText(_fromUtf8(""))
        self.lbl_id22_icon.setObjectName(_fromUtf8("lbl_id22_icon"))
        self.lbl_id31_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id31_icon.setGeometry(QtCore.QRect(730, 160, 40, 40))
        self.lbl_id31_icon.setText(_fromUtf8(""))
        self.lbl_id31_icon.setObjectName(_fromUtf8("lbl_id31_icon"))
        self.lbl_id22 = QtGui.QLabel(self.tab_2)
        self.lbl_id22.setGeometry(QtCore.QRect(540, 170, 120, 20))
        self.lbl_id22.setText(_fromUtf8(""))
        self.lbl_id22.setObjectName(_fromUtf8("lbl_id22"))
        self.lbl_id28_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id28_icon.setGeometry(QtCore.QRect(730, 10, 40, 40))
        self.lbl_id28_icon.setText(_fromUtf8(""))
        self.lbl_id28_icon.setObjectName(_fromUtf8("lbl_id28_icon"))
        self.lbl_id26_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id26_icon.setGeometry(QtCore.QRect(490, 360, 40, 40))
        self.lbl_id26_icon.setText(_fromUtf8(""))
        self.lbl_id26_icon.setObjectName(_fromUtf8("lbl_id26_icon"))
        self.lbl_id27 = QtGui.QLabel(self.tab_2)
        self.lbl_id27.setGeometry(QtCore.QRect(540, 420, 180, 20))
        self.lbl_id27.setText(_fromUtf8(""))
        self.lbl_id27.setObjectName(_fromUtf8("lbl_id27"))
        self.lbl_id29_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id29_icon.setGeometry(QtCore.QRect(730, 60, 40, 40))
        self.lbl_id29_icon.setText(_fromUtf8(""))
        self.lbl_id29_icon.setObjectName(_fromUtf8("lbl_id29_icon"))
        self.lbl_id30 = QtGui.QLabel(self.tab_2)
        self.lbl_id30.setGeometry(QtCore.QRect(780, 120, 120, 20))
        self.lbl_id30.setText(_fromUtf8(""))
        self.lbl_id30.setObjectName(_fromUtf8("lbl_id30"))
        self.lbl_id30_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id30_icon.setGeometry(QtCore.QRect(730, 110, 40, 40))
        self.lbl_id30_icon.setText(_fromUtf8(""))
        self.lbl_id30_icon.setObjectName(_fromUtf8("lbl_id30_icon"))
        self.lbl_id28 = QtGui.QLabel(self.tab_2)
        self.lbl_id28.setGeometry(QtCore.QRect(780, 20, 120, 20))
        self.lbl_id28.setText(_fromUtf8(""))
        self.lbl_id28.setObjectName(_fromUtf8("lbl_id28"))
        self.lbl_id21 = QtGui.QLabel(self.tab_2)
        self.lbl_id21.setGeometry(QtCore.QRect(540, 120, 120, 20))
        self.lbl_id21.setText(_fromUtf8(""))
        self.lbl_id21.setObjectName(_fromUtf8("lbl_id21"))
        self.lbl_id34 = QtGui.QLabel(self.tab_2)
        self.lbl_id34.setGeometry(QtCore.QRect(780, 320, 120, 20))
        self.lbl_id34.setText(_fromUtf8(""))
        self.lbl_id34.setObjectName(_fromUtf8("lbl_id34"))
        self.lbl_id26 = QtGui.QLabel(self.tab_2)
        self.lbl_id26.setGeometry(QtCore.QRect(540, 370, 120, 20))
        self.lbl_id26.setText(_fromUtf8(""))
        self.lbl_id26.setObjectName(_fromUtf8("lbl_id26"))
        self.lbl_id27_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id27_icon.setGeometry(QtCore.QRect(490, 410, 40, 40))
        self.lbl_id27_icon.setText(_fromUtf8(""))
        self.lbl_id27_icon.setObjectName(_fromUtf8("lbl_id27_icon"))
        self.lbl_id21_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id21_icon.setGeometry(QtCore.QRect(490, 110, 40, 40))
        self.lbl_id21_icon.setText(_fromUtf8(""))
        self.lbl_id21_icon.setObjectName(_fromUtf8("lbl_id21_icon"))
        self.lbl_id29 = QtGui.QLabel(self.tab_2)
        self.lbl_id29.setGeometry(QtCore.QRect(780, 70, 120, 20))
        self.lbl_id29.setText(_fromUtf8(""))
        self.lbl_id29.setObjectName(_fromUtf8("lbl_id29"))
        self.lbl_id35_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id35_icon.setGeometry(QtCore.QRect(730, 360, 40, 40))
        self.lbl_id35_icon.setText(_fromUtf8(""))
        self.lbl_id35_icon.setObjectName(_fromUtf8("lbl_id35_icon"))
        self.lbl_id32 = QtGui.QLabel(self.tab_2)
        self.lbl_id32.setGeometry(QtCore.QRect(780, 220, 120, 20))
        self.lbl_id32.setText(_fromUtf8(""))
        self.lbl_id32.setObjectName(_fromUtf8("lbl_id32"))
        self.lbl_id23_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id23_icon.setGeometry(QtCore.QRect(490, 210, 40, 40))
        self.lbl_id23_icon.setText(_fromUtf8(""))
        self.lbl_id23_icon.setObjectName(_fromUtf8("lbl_id23_icon"))
        self.lbl_id25_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id25_icon.setGeometry(QtCore.QRect(490, 310, 40, 40))
        self.lbl_id25_icon.setText(_fromUtf8(""))
        self.lbl_id25_icon.setObjectName(_fromUtf8("lbl_id25_icon"))
        self.lbl_id25 = QtGui.QLabel(self.tab_2)
        self.lbl_id25.setGeometry(QtCore.QRect(540, 320, 120, 20))
        self.lbl_id25.setText(_fromUtf8(""))
        self.lbl_id25.setObjectName(_fromUtf8("lbl_id25"))
        self.lbl_id20 = QtGui.QLabel(self.tab_2)
        self.lbl_id20.setGeometry(QtCore.QRect(540, 70, 120, 20))
        self.lbl_id20.setText(_fromUtf8(""))
        self.lbl_id20.setObjectName(_fromUtf8("lbl_id20"))
        self.lbl_id33 = QtGui.QLabel(self.tab_2)
        self.lbl_id33.setGeometry(QtCore.QRect(780, 270, 120, 20))
        self.lbl_id33.setText(_fromUtf8(""))
        self.lbl_id33.setObjectName(_fromUtf8("lbl_id33"))
        self.lbl_id20_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id20_icon.setGeometry(QtCore.QRect(490, 60, 40, 40))
        self.lbl_id20_icon.setText(_fromUtf8(""))
        self.lbl_id20_icon.setObjectName(_fromUtf8("lbl_id20_icon"))
        self.lbl_id24_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id24_icon.setGeometry(QtCore.QRect(490, 260, 40, 40))
        self.lbl_id24_icon.setText(_fromUtf8(""))
        self.lbl_id24_icon.setObjectName(_fromUtf8("lbl_id24_icon"))
        self.lbl_id36 = QtGui.QLabel(self.tab_2)
        self.lbl_id36.setGeometry(QtCore.QRect(780, 420, 120, 20))
        self.lbl_id36.setText(_fromUtf8(""))
        self.lbl_id36.setObjectName(_fromUtf8("lbl_id36"))
        self.lbl_id24 = QtGui.QLabel(self.tab_2)
        self.lbl_id24.setGeometry(QtCore.QRect(540, 270, 120, 20))
        self.lbl_id24.setText(_fromUtf8(""))
        self.lbl_id24.setObjectName(_fromUtf8("lbl_id24"))
        self.lbl_id36_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id36_icon.setGeometry(QtCore.QRect(730, 410, 40, 40))
        self.lbl_id36_icon.setText(_fromUtf8(""))
        self.lbl_id36_icon.setObjectName(_fromUtf8("lbl_id36_icon"))
        self.lbl_id38_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id38_icon.setGeometry(QtCore.QRect(730, 510, 40, 40))
        self.lbl_id38_icon.setText(_fromUtf8(""))
        self.lbl_id38_icon.setObjectName(_fromUtf8("lbl_id38_icon"))
        self.lbl_id37 = QtGui.QLabel(self.tab_2)
        self.lbl_id37.setGeometry(QtCore.QRect(780, 470, 120, 20))
        self.lbl_id37.setText(_fromUtf8(""))
        self.lbl_id37.setObjectName(_fromUtf8("lbl_id37"))
        self.lbl_id38 = QtGui.QLabel(self.tab_2)
        self.lbl_id38.setGeometry(QtCore.QRect(780, 520, 120, 20))
        self.lbl_id38.setText(_fromUtf8(""))
        self.lbl_id38.setObjectName(_fromUtf8("lbl_id38"))
        self.lbl_id37_icon = QtGui.QLabel(self.tab_2)
        self.lbl_id37_icon.setGeometry(QtCore.QRect(730, 460, 40, 40))
        self.lbl_id37_icon.setText(_fromUtf8(""))
        self.lbl_id37_icon.setObjectName(_fromUtf8("lbl_id37_icon"))
        self.btn_id1 = QtGui.QPushButton(self.tab_2)
        self.btn_id1.setEnabled(True)
        self.btn_id1.setGeometry(QtCore.QRect(180, 20, 60, 20))
        self.btn_id1.setObjectName(_fromUtf8("btn_id1"))
        self.btn_id2 = QtGui.QPushButton(self.tab_2)
        self.btn_id2.setGeometry(QtCore.QRect(180, 70, 60, 20))
        self.btn_id2.setObjectName(_fromUtf8("btn_id2"))
        self.btn_id5 = QtGui.QPushButton(self.tab_2)
        self.btn_id5.setGeometry(QtCore.QRect(180, 220, 60, 20))
        self.btn_id5.setObjectName(_fromUtf8("btn_id5"))
        self.btn_id3 = QtGui.QPushButton(self.tab_2)
        self.btn_id3.setGeometry(QtCore.QRect(180, 120, 60, 20))
        self.btn_id3.setObjectName(_fromUtf8("btn_id3"))
        self.btn_id4 = QtGui.QPushButton(self.tab_2)
        self.btn_id4.setGeometry(QtCore.QRect(180, 170, 60, 20))
        self.btn_id4.setObjectName(_fromUtf8("btn_id4"))
        self.btn_id7 = QtGui.QPushButton(self.tab_2)
        self.btn_id7.setGeometry(QtCore.QRect(180, 320, 60, 20))
        self.btn_id7.setObjectName(_fromUtf8("btn_id7"))
        self.btn_id8 = QtGui.QPushButton(self.tab_2)
        self.btn_id8.setGeometry(QtCore.QRect(180, 370, 60, 20))
        self.btn_id8.setObjectName(_fromUtf8("btn_id8"))
        self.btn_id6 = QtGui.QPushButton(self.tab_2)
        self.btn_id6.setGeometry(QtCore.QRect(180, 270, 60, 20))
        self.btn_id6.setObjectName(_fromUtf8("btn_id6"))
        self.btn_id9 = QtGui.QPushButton(self.tab_2)
        self.btn_id9.setGeometry(QtCore.QRect(180, 420, 60, 20))
        self.btn_id9.setObjectName(_fromUtf8("btn_id9"))
        self.btn_id17 = QtGui.QPushButton(self.tab_2)
        self.btn_id17.setGeometry(QtCore.QRect(420, 370, 60, 20))
        self.btn_id17.setObjectName(_fromUtf8("btn_id17"))
        self.btn_id18 = QtGui.QPushButton(self.tab_2)
        self.btn_id18.setGeometry(QtCore.QRect(420, 420, 60, 20))
        self.btn_id18.setObjectName(_fromUtf8("btn_id18"))
        self.btn_id10 = QtGui.QPushButton(self.tab_2)
        self.btn_id10.setGeometry(QtCore.QRect(420, 20, 60, 20))
        self.btn_id10.setObjectName(_fromUtf8("btn_id10"))
        self.btn_id16 = QtGui.QPushButton(self.tab_2)
        self.btn_id16.setGeometry(QtCore.QRect(420, 320, 60, 20))
        self.btn_id16.setObjectName(_fromUtf8("btn_id16"))
        self.btn_id11 = QtGui.QPushButton(self.tab_2)
        self.btn_id11.setGeometry(QtCore.QRect(420, 70, 60, 20))
        self.btn_id11.setObjectName(_fromUtf8("btn_id11"))
        self.btn_id15 = QtGui.QPushButton(self.tab_2)
        self.btn_id15.setGeometry(QtCore.QRect(420, 270, 60, 20))
        self.btn_id15.setObjectName(_fromUtf8("btn_id15"))
        self.btn_id14 = QtGui.QPushButton(self.tab_2)
        self.btn_id14.setGeometry(QtCore.QRect(420, 220, 60, 20))
        self.btn_id14.setObjectName(_fromUtf8("btn_id14"))
        self.btn_id13 = QtGui.QPushButton(self.tab_2)
        self.btn_id13.setGeometry(QtCore.QRect(420, 170, 60, 20))
        self.btn_id13.setObjectName(_fromUtf8("btn_id13"))
        self.btn_id12 = QtGui.QPushButton(self.tab_2)
        self.btn_id12.setGeometry(QtCore.QRect(420, 120, 60, 20))
        self.btn_id12.setObjectName(_fromUtf8("btn_id12"))
        self.btn_id26 = QtGui.QPushButton(self.tab_2)
        self.btn_id26.setGeometry(QtCore.QRect(660, 370, 60, 20))
        self.btn_id26.setObjectName(_fromUtf8("btn_id26"))
        self.btn_id27 = QtGui.QPushButton(self.tab_2)
        self.btn_id27.setGeometry(QtCore.QRect(660, 420, 60, 20))
        self.btn_id27.setObjectName(_fromUtf8("btn_id27"))
        self.btn_id19 = QtGui.QPushButton(self.tab_2)
        self.btn_id19.setGeometry(QtCore.QRect(660, 20, 60, 20))
        self.btn_id19.setObjectName(_fromUtf8("btn_id19"))
        self.btn_id25 = QtGui.QPushButton(self.tab_2)
        self.btn_id25.setGeometry(QtCore.QRect(660, 320, 60, 20))
        self.btn_id25.setObjectName(_fromUtf8("btn_id25"))
        self.btn_id20 = QtGui.QPushButton(self.tab_2)
        self.btn_id20.setGeometry(QtCore.QRect(660, 70, 60, 20))
        self.btn_id20.setObjectName(_fromUtf8("btn_id20"))
        self.btn_id24 = QtGui.QPushButton(self.tab_2)
        self.btn_id24.setGeometry(QtCore.QRect(660, 270, 60, 20))
        self.btn_id24.setObjectName(_fromUtf8("btn_id24"))
        self.btn_id23 = QtGui.QPushButton(self.tab_2)
        self.btn_id23.setGeometry(QtCore.QRect(660, 220, 60, 20))
        self.btn_id23.setObjectName(_fromUtf8("btn_id23"))
        self.btn_id22 = QtGui.QPushButton(self.tab_2)
        self.btn_id22.setGeometry(QtCore.QRect(660, 170, 60, 20))
        self.btn_id22.setObjectName(_fromUtf8("btn_id22"))
        self.btn_id21 = QtGui.QPushButton(self.tab_2)
        self.btn_id21.setGeometry(QtCore.QRect(660, 120, 60, 20))
        self.btn_id21.setObjectName(_fromUtf8("btn_id21"))
        self.btn_id35 = QtGui.QPushButton(self.tab_2)
        self.btn_id35.setGeometry(QtCore.QRect(900, 370, 60, 20))
        self.btn_id35.setObjectName(_fromUtf8("btn_id35"))
        self.btn_id36 = QtGui.QPushButton(self.tab_2)
        self.btn_id36.setGeometry(QtCore.QRect(900, 420, 60, 20))
        self.btn_id36.setObjectName(_fromUtf8("btn_id36"))
        self.btn_id28 = QtGui.QPushButton(self.tab_2)
        self.btn_id28.setGeometry(QtCore.QRect(900, 20, 60, 20))
        self.btn_id28.setObjectName(_fromUtf8("btn_id28"))
        self.btn_id34 = QtGui.QPushButton(self.tab_2)
        self.btn_id34.setGeometry(QtCore.QRect(900, 320, 60, 20))
        self.btn_id34.setObjectName(_fromUtf8("btn_id34"))
        self.btn_id29 = QtGui.QPushButton(self.tab_2)
        self.btn_id29.setGeometry(QtCore.QRect(900, 70, 60, 20))
        self.btn_id29.setObjectName(_fromUtf8("btn_id29"))
        self.btn_id33 = QtGui.QPushButton(self.tab_2)
        self.btn_id33.setGeometry(QtCore.QRect(900, 270, 60, 20))
        self.btn_id33.setObjectName(_fromUtf8("btn_id33"))
        self.btn_id32 = QtGui.QPushButton(self.tab_2)
        self.btn_id32.setGeometry(QtCore.QRect(900, 220, 60, 20))
        self.btn_id32.setObjectName(_fromUtf8("btn_id32"))
        self.btn_id31 = QtGui.QPushButton(self.tab_2)
        self.btn_id31.setGeometry(QtCore.QRect(900, 170, 60, 20))
        self.btn_id31.setObjectName(_fromUtf8("btn_id31"))
        self.btn_id30 = QtGui.QPushButton(self.tab_2)
        self.btn_id30.setGeometry(QtCore.QRect(900, 120, 60, 20))
        self.btn_id30.setObjectName(_fromUtf8("btn_id30"))
        self.btn_id37 = QtGui.QPushButton(self.tab_2)
        self.btn_id37.setGeometry(QtCore.QRect(900, 470, 60, 20))
        self.btn_id37.setObjectName(_fromUtf8("btn_id37"))
        self.btn_id38 = QtGui.QPushButton(self.tab_2)
        self.btn_id38.setGeometry(QtCore.QRect(900, 520, 60, 20))
        self.btn_id38.setObjectName(_fromUtf8("btn_id38"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Project T", None))
        self.lbl_lumber.setText(_translate("MainWindow", "0/0/0", None))
        self.label_2.setText(_translate("MainWindow", "TextLabel", None))
        self.btn_update.setText(_translate("MainWindow", "Update", None))
        self.label.setText(_translate("MainWindow", "TextLabel", None))
        self.lbl_clay.setText(_translate("MainWindow", "0/0/0", None))
        self.lbl_iron.setText(_translate("MainWindow", "0/0/0", None))
        self.lbl_crop.setText(_translate("MainWindow", "0/0/0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1", None))
        self.btn_id1.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id2.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id5.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id3.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id4.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id7.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id8.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id6.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id9.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id17.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id18.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id10.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id16.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id11.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id15.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id14.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id13.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id12.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id26.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id27.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id19.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id25.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id20.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id24.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id23.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id22.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id21.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id35.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id36.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id28.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id34.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id29.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id33.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id32.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id31.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id30.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id37.setText(_translate("MainWindow", "Upgrade", None))
        self.btn_id38.setText(_translate("MainWindow", "Upgrade", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

